#!/usr/bin/env python3
#
# Emit a C header with the LiteX SoC's CSR table, pre-built from the
# generated csr.json so litex.csr_read / litex.csr_write can resolve a
# register name to an address at runtime with a simple bsearch.
#
# Invoked by the port Makefile with:
#
#     gen_csr_table.py <BUILD_DIRECTORY>/software/include/generated/csr.json \
#                      <build>/genhdr/litex_csr_table.h
#
# The output is tracked as a build artefact; it's regenerated whenever the
# LiteX SoC is re-generated. We deliberately don't ship a pre-baked table —
# it's per-SoC and must match the CSRs the firmware was compiled against.
#
# Copyright (c) 2026 Florent Kermarrec <f.kermarrec@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause

import argparse
import json
import sys


# Map csr.json 'type' strings to the compact 1-byte enum we store in the
# table; these are the values we later compare against in modlitex.c.
TYPE_ENUM = {"ro": 0, "rw": 1, "wo": 2}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("csr_json", help="path to generated csr.json")
    parser.add_argument("out_header", help="path to the header to write")
    args = parser.parse_args()

    with open(args.csr_json) as f:
        spec = json.load(f)

    regs = spec.get("csr_registers", {})
    # Sort by name so the C-side can do a binary search in O(log n). 200
    # CSRs is the realistic upper bound; linear scan would be fine, but
    # sorted is cheap and lets us bsearch if we ever care.
    items = sorted(regs.items())

    # IRQ table: every "<prefix>_interrupt" constant tells us which CPU
    # IRQ bit a peripheral's EventManager is wired to. Used by isr.c to
    # dispatch to Python handlers registered via litex.EventManager.irq.
    irqs = sorted(
        (k[: -len("_interrupt")], int(v))
        for k, v in spec.get("constants", {}).items()
        if k.endswith("_interrupt") and isinstance(v, int)
    )

    with open(args.out_header, "w") as f:
        f.write("// Auto-generated by ports/litex/tools/gen_csr_table.py.\n")
        f.write("// Do not edit by hand — re-run the LiteX SoC generation.\n\n")
        f.write("#ifndef MICROPY_LITEX_CSR_TABLE_H\n")
        f.write("#define MICROPY_LITEX_CSR_TABLE_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("typedef struct {\n")
        f.write("    const char *name;\n")
        f.write("    uint32_t addr;\n")
        f.write("    uint8_t size;   // number of CSR words this register spans\n")
        f.write("    uint8_t type;   // 0=ro, 1=rw, 2=wo\n")
        f.write("} litex_csr_entry_t;\n\n")
        f.write("static const litex_csr_entry_t litex_csr_table[] = {\n")
        for name, info in items:
            f.write('    {"%s", 0x%08x, %d, %d},\n' % (
                name, info["addr"], info["size"],
                TYPE_ENUM.get(info["type"], 1)))
        f.write("};\n\n")
        f.write("#define LITEX_CSR_TABLE_SIZE "
                "(sizeof(litex_csr_table)/sizeof(litex_csr_table[0]))\n\n")

        # IRQ table: name -> CPU IRQ bit, for litex.EventManager.irq dispatch.
        f.write("typedef struct {\n")
        f.write("    const char *prefix;\n")
        f.write("    uint8_t bit;\n")
        f.write("} litex_irq_entry_t;\n\n")
        f.write("static const litex_irq_entry_t litex_irq_table[] = {\n")
        for prefix, bit in irqs:
            f.write('    {"%s", %d},\n' % (prefix, bit))
        f.write("};\n\n")
        f.write("#define LITEX_IRQ_TABLE_SIZE "
                "(sizeof(litex_irq_table)/sizeof(litex_irq_table[0]))\n\n")

        f.write("#endif // MICROPY_LITEX_CSR_TABLE_H\n")


if __name__ == "__main__":
    main()
